trigger:
  - main

pool:
  name: DevOpsLinuxPoolNew

stages:
  - stage: Build
    jobs:
      - job: BuildBackend
        displayName: 'Build Backend'
        steps:
          - task: GoTool@0
            inputs:
              version: '1.20'
          - script: |
              cd go_backend
              go build -v -o app-backend
            displayName: 'Build Go Backend'
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(System.DefaultWorkingDirectory)/go_backend/app-backend'
              artifactName: 'BackendArtifact'
            displayName: 'Publish Backend Artifact'

      - job: BuildFrontend
        displayName: 'Build Frontend'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
          - script: |
              cd react_frontend
              npm install
              npm run build
            displayName: 'Build React Frontend'
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(System.DefaultWorkingDirectory)/react_frontend/build'
              artifactName: 'FrontendArtifact'
            displayName: 'Publish Frontend Artifact'

  - stage: Test
    dependsOn: Build
    jobs:
      - job: TestGoBackend
        displayName: 'Test Go Backend'
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              artifactName: 'BackendArtifact'
            displayName: 'Download Backend Artifact'

          - task: GoTool@0
            inputs:
              version: '1.20'

          - script: |
              # İndirilen artifact'ın yolu genellikle $(Pipeline.Workspace)/<artifact_adı> olacaktır.
              # Örneğin: $(Pipeline.Workspace)/BackendArtifact/app-backend
              # Eğer go test sadece kaynak kodu kullanıyorsa, bu indirme adımına ihtiyaç duymayabilirsiniz.
              # Ancak derlenmiş çıktıyı test ediyorsanız, bu yol gereklidir.
              cd $(System.DefaultWorkingDirectory)/go_backend 
              go test -v simple_test.go
            displayName: 'Run Go Backend Tests'

      - job: TestReactFrontend
        displayName: 'Test React Frontend'
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              artifactName: 'FrontendArtifact'
            displayName: 'Download Frontend Artifact'

          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'

          - script: |
              cd $(System.DefaultWorkingDirectory)/react_frontend
              npm install
              npm test -- --watchAll=false
            displayName: 'Run React Frontend Tests'