trigger:
  - main

pool:
  vmImage: DevOpsLinuxPoolNew

stages:
  - stage: Test
    jobs:
      - job: TestGoBackend
        steps:
          - task: GoTool@0
            inputs:
              version: '1.20'
          - script: |
              cd go_backend
              go test -v simple_test.go
            displayName: 'Run Go backend tests'

      - job: TestReactFrontend
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
          - script: |
              cd react_frontend
              npm install
              npm test -- --watchAll=false
            displayName: 'Run React frontend tests'

  - stage: Build
    dependsOn: Test
    jobs:
      - job: BuildBackend
        steps:
          - task: GoTool@0
            inputs:
              version: '1.20'
          - script: |
              cd go_backend
              go build -v
            displayName: 'Build Go backend'

      - job: BuildFrontend
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
          - script: |
              cd react_frontend
              npm install
              npm run build
            displayName: 'Build React frontend'
