apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: todolist
type: Opaque
data:
  DB_USER: dG9kb2xpc3RfdXNlcg==
  DB_PASSWORD: TG9jYWxwYXNzLg==
  DB_ROOT_PASSWORD: TG9jYWxwYXNzLg==
  JWT_SECRET: and0c2VjcmV0a2V5
